FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libmariadb3 \
    libmariadb-dev \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app
COPY . .
CMD ["python", "main.py"]